Update to support ESP-IDF v5 in develop branch
lvgl/lvgl_esp32_drivers pull request #186
Opened 2022-03-09 00:16 UTC by rashedtalukder

Shifting PR https://github.com/lvgl/lvgl_esp32_drivers/pull/184 to develop branch instead. This has all the past changes. Tested against ESP-IDF prerelease-v5.0 and release-v4.4 on the M5Stack Core2 for AWS using a modified version of this example: https://github.com/lvgl/lv_port_esp32/tree/feat/new_driver_test

ESP-IDF v5.0.0 incorporates a major update to the real-time kernel and number of other changes. This is my quick stab at adding support for the new toolchain version before the official release. Tested on the M5Stack Core2 for AWS IoT EduKit and works great.

There are memory and performance advantages to using pdMS_TO_TICKS instead of portTICK_PERIOD_MS or the deprecated portTICK_RATE_MS macros. That's why you'll see mostly universal changes that switches to that.

2022-03-09 06:29 UTC, C47D commented on lv_port/esp_lcd_backlight.c
> +#include "rom/gpio.h"
This particular include is causing the CI to fail

2022-03-09 12:32 UTC, tore-espressif requested changes
We can merge after `#include "rom/gpio.h"` includes are removed, thanks for your patience @rashedtalukder !

2022-03-19 02:35 UTC, rashedtalukder commented
Sorry for the delay in getting time for this. I've gone ahead and removed all the `#include "rom/gpio.h"` but maintained compatibility with ESP-IDF v5.0 as it sits currently.

2022-03-21 07:32 UTC, tore-espressif approved these changes

2022-05-13 03:15 UTC, merged